<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PermissionCatalogSeeder extends Seeder
{
    /**
     * @var list<array{key: string, name: string, description: string|null, domain: string}>
     */
    private const PERMISSIONS = [
        ['key' => 'organization.read', 'name' => 'Read Organization', 'description' => null, 'domain' => 'organization'],
        ['key' => 'organization.update', 'name' => 'Update Organization', 'description' => null, 'domain' => 'organization'],
        ['key' => 'organization.archive', 'name' => 'Archive Organization', 'description' => null, 'domain' => 'organization'],
        ['key' => 'platform.read', 'name' => 'Read Platform Administration', 'description' => null, 'domain' => 'platform'],
        ['key' => 'permissions.read', 'name' => 'Read Permission Catalog', 'description' => null, 'domain' => 'platform'],
        ['key' => 'runtime.read', 'name' => 'Read Platform Runtime', 'description' => null, 'domain' => 'platform'],
        ['key' => 'settings.read', 'name' => 'Read Platform Settings', 'description' => null, 'domain' => 'platform'],
        ['key' => 'diagnostics.read', 'name' => 'Read Platform Diagnostics', 'description' => null, 'domain' => 'platform'],
        ['key' => 'members.read', 'name' => 'Read Members', 'description' => null, 'domain' => 'organization'],
        ['key' => 'members.invite', 'name' => 'Invite Members', 'description' => null, 'domain' => 'organization'],
        ['key' => 'members.update', 'name' => 'Update Members', 'description' => null, 'domain' => 'organization'],
        ['key' => 'members.remove', 'name' => 'Remove Members', 'description' => null, 'domain' => 'organization'],
        ['key' => 'roles.read', 'name' => 'Read Roles', 'description' => null, 'domain' => 'organization'],
        ['key' => 'roles.manage', 'name' => 'Manage Roles', 'description' => null, 'domain' => 'organization'],
        ['key' => 'workspace.read', 'name' => 'Read Workspaces', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.create', 'name' => 'Create Workspaces', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.update', 'name' => 'Update Workspaces', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.archive', 'name' => 'Archive Workspaces', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.applications.read', 'name' => 'Read Workspace Applications', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.applications.enable', 'name' => 'Enable Workspace Applications', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.applications.configure', 'name' => 'Configure Workspace Applications', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'workspace.applications.manage', 'name' => 'Manage Workspace Applications', 'description' => null, 'domain' => 'workspace'],
        ['key' => 'applications.read', 'name' => 'Read Applications', 'description' => null, 'domain' => 'application'],
        ['key' => 'applications.install', 'name' => 'Install Applications', 'description' => null, 'domain' => 'application'],
        ['key' => 'applications.configure', 'name' => 'Configure Applications', 'description' => null, 'domain' => 'application'],
        ['key' => 'applications.uninstall', 'name' => 'Uninstall Applications', 'description' => null, 'domain' => 'application'],
        ['key' => 'audit.read', 'name' => 'Read Audit Events', 'description' => null, 'domain' => 'audit'],
        ['key' => 'notifications.read', 'name' => 'Read Notifications', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.send', 'name' => 'Send Notifications', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.manage', 'name' => 'Manage Notifications', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.templates', 'name' => 'Manage Notification Templates', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.preferences', 'name' => 'Manage Notification Preferences', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.broadcast', 'name' => 'Broadcast Notifications', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.schedule', 'name' => 'Schedule Notifications', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'notifications.digest', 'name' => 'Manage Notification Digests', 'description' => null, 'domain' => 'notifications'],
        ['key' => 'reference.read', 'name' => 'Read Reference Data', 'description' => null, 'domain' => 'reference'],
        ['key' => 'files.read', 'name' => 'Read Files', 'description' => null, 'domain' => 'files'],
        ['key' => 'files.upload', 'name' => 'Upload Files', 'description' => null, 'domain' => 'files'],
        ['key' => 'files.manage', 'name' => 'Manage Files', 'description' => null, 'domain' => 'files'],
        ['key' => 'jobs.read', 'name' => 'Read Jobs', 'description' => null, 'domain' => 'jobs'],
        ['key' => 'jobs.dispatch', 'name' => 'Dispatch Jobs', 'description' => null, 'domain' => 'jobs'],
        ['key' => 'jobs.manage', 'name' => 'Manage Jobs', 'description' => null, 'domain' => 'jobs'],
        ['key' => 'scheduler.read', 'name' => 'Read Scheduled Tasks', 'description' => null, 'domain' => 'scheduler'],
        ['key' => 'scheduler.manage', 'name' => 'Manage Scheduled Tasks', 'description' => null, 'domain' => 'scheduler'],
        ['key' => 'search.read', 'name' => 'Read Search', 'description' => null, 'domain' => 'search'],
        ['key' => 'search.manage', 'name' => 'Manage Search', 'description' => null, 'domain' => 'search'],
        ['key' => 'workflow.read', 'name' => 'Read Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.manage', 'name' => 'Manage Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.publish', 'name' => 'Publish Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.execute', 'name' => 'Execute Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.runtime.read', 'name' => 'Read Workflow Runtime', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'task.read', 'name' => 'Read Tasks', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'task.manage', 'name' => 'Manage Tasks', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'approval.read', 'name' => 'Read Approvals', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'approval.decide', 'name' => 'Decide Approvals', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.automation.read', 'name' => 'Read Workflow Automation', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.automation.manage', 'name' => 'Manage Workflow Automation', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.designer.read', 'name' => 'Read Workflow Designer', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.designer.manage', 'name' => 'Manage Workflow Designer', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.designer.import', 'name' => 'Import Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.designer.export', 'name' => 'Export Workflows', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.marketplace.read', 'name' => 'Read Workflow Marketplace', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.marketplace.install', 'name' => 'Install Workflow Marketplace Packages', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.marketplace.publish', 'name' => 'Publish Workflow Marketplace Packages', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.marketplace.manage', 'name' => 'Manage Workflow Marketplace Packages', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'workflow.marketplace.export', 'name' => 'Export Workflow Marketplace Packages', 'description' => null, 'domain' => 'workflow'],
        ['key' => 'business.modules.read', 'name' => 'Read Business Modules', 'description' => null, 'domain' => 'business'],
        ['key' => 'business.modules.install', 'name' => 'Install Business Modules', 'description' => null, 'domain' => 'business'],
        ['key' => 'business.modules.manage', 'name' => 'Manage Business Modules', 'description' => null, 'domain' => 'business'],
        ['key' => 'business.modules.develop', 'name' => 'Develop Business Modules', 'description' => null, 'domain' => 'business'],
        ['key' => 'entities.read', 'name' => 'Read Entities', 'description' => null, 'domain' => 'business'],
        ['key' => 'entities.manage', 'name' => 'Manage Entities', 'description' => null, 'domain' => 'business'],
        ['key' => 'entities.comment', 'name' => 'Comment on Entities', 'description' => null, 'domain' => 'business'],
        ['key' => 'entities.tag', 'name' => 'Tag Entities', 'description' => null, 'domain' => 'business'],
        ['key' => 'forms.read', 'name' => 'Read Forms', 'description' => null, 'domain' => 'business'],
        ['key' => 'forms.manage', 'name' => 'Manage Forms', 'description' => null, 'domain' => 'business'],
        ['key' => 'forms.submit', 'name' => 'Submit Forms', 'description' => null, 'domain' => 'business'],
        ['key' => 'forms.draft', 'name' => 'Manage Form Drafts', 'description' => null, 'domain' => 'business'],
        ['key' => 'tables.read', 'name' => 'Read Tables', 'description' => null, 'domain' => 'business'],
        ['key' => 'tables.manage', 'name' => 'Manage Tables', 'description' => null, 'domain' => 'business'],
        ['key' => 'tables.query', 'name' => 'Query Tables', 'description' => null, 'domain' => 'business'],
        ['key' => 'tables.export', 'name' => 'Export Tables', 'description' => null, 'domain' => 'business'],
        ['key' => 'dashboards.read', 'name' => 'Read Dashboards', 'description' => null, 'domain' => 'business'],
        ['key' => 'dashboards.manage', 'name' => 'Manage Dashboards', 'description' => null, 'domain' => 'business'],
        ['key' => 'dashboards.render', 'name' => 'Render Dashboards', 'description' => null, 'domain' => 'business'],
        ['key' => 'dashboards.export', 'name' => 'Export Dashboards', 'description' => null, 'domain' => 'business'],
        ['key' => 'reports.read', 'name' => 'Read Reports', 'description' => null, 'domain' => 'business'],
        ['key' => 'reports.manage', 'name' => 'Manage Reports', 'description' => null, 'domain' => 'business'],
        ['key' => 'reports.run', 'name' => 'Run Reports', 'description' => null, 'domain' => 'business'],
        ['key' => 'reports.export', 'name' => 'Export Reports', 'description' => null, 'domain' => 'business'],
        ['key' => 'reports.schedule', 'name' => 'Schedule Reports', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.read', 'name' => 'Read Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.create', 'name' => 'Create Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.update', 'name' => 'Update Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.delete', 'name' => 'Delete Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.restore', 'name' => 'Restore Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.link', 'name' => 'Link Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'data.records.manage', 'name' => 'Manage Entity Records', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.read', 'name' => 'Read Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.upload', 'name' => 'Upload Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.update', 'name' => 'Update Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.delete', 'name' => 'Delete Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.version', 'name' => 'Version Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.attach', 'name' => 'Attach Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'documents.manage', 'name' => 'Manage Documents', 'description' => null, 'domain' => 'business'],
        ['key' => 'rules.read', 'name' => 'Read Business Rules', 'description' => null, 'domain' => 'business'],
        ['key' => 'rules.manage', 'name' => 'Manage Business Rules', 'description' => null, 'domain' => 'business'],
        ['key' => 'rules.evaluate', 'name' => 'Evaluate Business Rules', 'description' => null, 'domain' => 'business'],
        ['key' => 'rules.execute', 'name' => 'Execute Business Rules', 'description' => null, 'domain' => 'business'],
        ['key' => 'rules.admin', 'name' => 'Administer Business Rules', 'description' => null, 'domain' => 'business'],
        ['key' => 'integrations.read', 'name' => 'Read Integrations', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'integrations.manage', 'name' => 'Manage Integrations', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'integrations.publish', 'name' => 'Publish Integration Events', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'integrations.dispatch', 'name' => 'Dispatch Integration Events', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'integrations.replay', 'name' => 'Replay Integration Events', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'integrations.admin', 'name' => 'Administer Integrations', 'description' => null, 'domain' => 'integrations'],
        ['key' => 'application.read', 'name' => 'Read Application Runtime', 'description' => null, 'domain' => 'application'],
        ['key' => 'application.manage', 'name' => 'Manage Application Runtime', 'description' => null, 'domain' => 'application'],
        ['key' => 'navigation.read', 'name' => 'Read Navigation', 'description' => null, 'domain' => 'application'],
        ['key' => 'navigation.manage', 'name' => 'Manage Navigation', 'description' => null, 'domain' => 'application'],
        ['key' => 'navigation.publish', 'name' => 'Publish Navigation', 'description' => null, 'domain' => 'application'],
        ['key' => 'navigation.personalize', 'name' => 'Personalize Navigation', 'description' => null, 'domain' => 'application'],
        ['key' => 'themes.read', 'name' => 'Read Themes', 'description' => null, 'domain' => 'ui'],
        ['key' => 'themes.manage', 'name' => 'Manage Themes', 'description' => null, 'domain' => 'ui'],
        ['key' => 'themes.publish', 'name' => 'Publish Themes', 'description' => null, 'domain' => 'ui'],
        ['key' => 'themes.brand', 'name' => 'Manage Theme Brand Profiles', 'description' => null, 'domain' => 'ui'],
        ['key' => 'personalization.read', 'name' => 'Read Personalization', 'description' => null, 'domain' => 'ui'],
        ['key' => 'personalization.write', 'name' => 'Write Personalization', 'description' => null, 'domain' => 'ui'],
        ['key' => 'personalization.manage', 'name' => 'Manage Personalization', 'description' => null, 'domain' => 'ui'],
        ['key' => 'personalization.admin', 'name' => 'Administer Personalization', 'description' => null, 'domain' => 'ui'],
        ['key' => 'ui.read', 'name' => 'Read UI Metadata', 'description' => null, 'domain' => 'ui'],
        ['key' => 'ui.manage', 'name' => 'Manage UI Metadata', 'description' => null, 'domain' => 'ui'],
        ['key' => 'ui.render', 'name' => 'Render UI Metadata', 'description' => null, 'domain' => 'ui'],
        ['key' => 'ui.personalize', 'name' => 'Personalize UI Metadata', 'description' => null, 'domain' => 'ui'],
        ['key' => 'hosteady.admin.read', 'name' => 'Read Hosteady Admin', 'description' => 'Read Hosteady Admin reference application.', 'domain' => 'application'],
        ['key' => 'hosteady.admin.manage', 'name' => 'Manage Hosteady Admin', 'description' => 'Manage Hosteady Admin operations.', 'domain' => 'application'],
        ['key' => 'hosteady.admin.configure', 'name' => 'Configure Hosteady Admin', 'description' => 'Configure Hosteady Admin settings.', 'domain' => 'application'],
        ['key' => 'hosteady.admin.reports.read', 'name' => 'Read Hosteady Admin Reports', 'description' => 'Read Hosteady Admin reports.', 'domain' => 'application'],
        ['key' => 'hosteady.admin.audit.read', 'name' => 'Read Hosteady Admin Audit', 'description' => 'Read Hosteady Admin audit events.', 'domain' => 'application'],
    ];

    public function run(): void
    {
        foreach (self::PERMISSIONS as $permission) {
            $existingPermission = Permission::query()
                ->where('key', $permission['key'])
                ->first();

            if ($existingPermission) {
                $existingPermission->update([
                    'name' => $permission['name'],
                    'description' => $permission['description'],
                    'domain' => $permission['domain'],
                ]);

                continue;
            }

            Permission::query()->create([
                'id' => (string) Str::uuid7(),
                'public_id' => (string) Str::uuid7(),
                'key' => $permission['key'],
                'name' => $permission['name'],
                'description' => $permission['description'],
                'domain' => $permission['domain'],
            ]);
        }
    }
}