<?php

use App\Http\Controllers\Api\V1\ApplicationCatalogController;
use App\Http\Controllers\Api\V1\Auth\LoginController;
use App\Http\Controllers\Api\V1\Auth\LogoutController;
use App\Http\Controllers\Api\V1\Auth\MeController;
use App\Http\Controllers\Api\V1\Auth\OrganizationsController;
use App\Http\Controllers\Api\V1\Tenant\ApplicationSettingDefinitionController;
use App\Http\Controllers\Api\V1\Tenant\AuditEventController;
use App\Http\Controllers\Api\V1\Tenant\ApplicationCatalogController as TenantApplicationCatalogController;
use App\Http\Controllers\Api\V1\Tenant\OrganizationApplicationController;
use App\Http\Controllers\Api\V1\Tenant\PlatformFileController;
use App\Http\Controllers\Api\V1\Tenant\PlatformJobController;
use App\Http\Controllers\Api\V1\Tenant\ScheduledTaskController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseNotificationController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseBusinessRuleController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseIntegrationController;
use App\Http\Controllers\Api\V1\Tenant\ReferenceDataController;
use App\Http\Controllers\Api\V1\Tenant\SearchController;
use App\Http\Controllers\Api\V1\Tenant\TenantContextController;
use App\Http\Controllers\Api\V1\Tenant\ApprovalController;
use App\Http\Controllers\Api\V1\Tenant\HumanTaskController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowAutomationController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowDesignerController;
use App\Http\Controllers\Api\V1\Tenant\BusinessModuleController;
use App\Http\Controllers\Api\V1\Tenant\DynamicFormController;
use App\Http\Controllers\Api\V1\Tenant\DynamicTableController;
use App\Http\Controllers\Api\V1\Tenant\DynamicDashboardController;
use App\Http\Controllers\Api\V1\Tenant\DynamicReportController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseDocumentController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseEntityController;
use App\Http\Controllers\Api\V1\Tenant\EnterpriseEntityRecordController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowMarketplaceController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowCategoryController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowDefinitionController;
use App\Http\Controllers\Api\V1\Tenant\WorkflowInstanceController;
use App\Http\Controllers\Api\V1\Tenant\WorkspaceApplicationController;
use App\Http\Controllers\Api\V1\Tenant\WorkspaceApplicationSettingsController;
use App\Http\Controllers\Api\V1\Tenant\WorkspaceRuntimeController;
use App\Http\Controllers\Api\V1\Tenant\WorkspaceRuntimeHealthController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('auth/login', LoginController::class)
        ->middleware('throttle:6,1');

    Route::middleware('auth:sanctum')->group(function () {
        Route::post('auth/logout', LogoutController::class);
        Route::get('auth/me', MeController::class);
        Route::get('auth/organizations', OrganizationsController::class);
        Route::get('applications/catalog', ApplicationCatalogController::class);

        Route::middleware('tenant.context')->group(function () {
            Route::get('tenant/context', TenantContextController::class);
            Route::get('tenant/applications/catalog', TenantApplicationCatalogController::class);
            Route::get('tenant/applications', [OrganizationApplicationController::class, 'index']);
            Route::post('tenant/applications', [OrganizationApplicationController::class, 'store']);
            Route::patch('tenant/applications/{installationPublicId}/enable', [OrganizationApplicationController::class, 'enable']);
            Route::patch('tenant/applications/{installationPublicId}/disable', [OrganizationApplicationController::class, 'disable']);
            Route::delete('tenant/applications/{installationPublicId}', [OrganizationApplicationController::class, 'destroy']);
            Route::get('tenant/applications/{applicationPublicId}/settings/definitions', ApplicationSettingDefinitionController::class);
            Route::get('tenant/workspace/applications', [WorkspaceApplicationController::class, 'index']);
            Route::get('tenant/workspace/applications/available', [WorkspaceApplicationController::class, 'available']);
            Route::post('tenant/workspace/applications', [WorkspaceApplicationController::class, 'store']);
            Route::patch('tenant/workspace/applications/{workspaceApplicationPublicId}/enable', [WorkspaceApplicationController::class, 'enable']);
            Route::patch('tenant/workspace/applications/{workspaceApplicationPublicId}/disable', [WorkspaceApplicationController::class, 'disable']);
            Route::patch('tenant/workspace/applications/{workspaceApplicationPublicId}/archive', [WorkspaceApplicationController::class, 'archive']);
            Route::delete('tenant/workspace/applications/{workspaceApplicationPublicId}', [WorkspaceApplicationController::class, 'destroy']);
            Route::get('tenant/workspace/settings', [WorkspaceApplicationSettingsController::class, 'index']);
            Route::put('tenant/workspace/settings', [WorkspaceApplicationSettingsController::class, 'update']);
            Route::post('tenant/workspace/settings/reset', [WorkspaceApplicationSettingsController::class, 'reset']);
            Route::get('tenant/workspace/settings/history', [WorkspaceApplicationSettingsController::class, 'history']);
            Route::get('tenant/workspace/runtime', WorkspaceRuntimeController::class);
            Route::get('tenant/workspace/runtime/health', WorkspaceRuntimeHealthController::class);
            Route::get('tenant/audit/events', [AuditEventController::class, 'index'])
                ->name('tenant.audit.events.index');
            Route::get('tenant/audit/summary', [AuditEventController::class, 'summary'])
                ->name('tenant.audit.summary');
            Route::get('tenant/audit/events/{eventPublicId}', [AuditEventController::class, 'show'])
                ->name('tenant.audit.events.show');
            Route::get('tenant/notifications/templates', [EnterpriseNotificationController::class, 'templates']);
            Route::post('tenant/notifications/templates', [EnterpriseNotificationController::class, 'storeTemplate']);
            Route::get('tenant/notifications/preferences', [EnterpriseNotificationController::class, 'preferences']);
            Route::patch('tenant/notifications/preferences', [EnterpriseNotificationController::class, 'updatePreferences']);
            Route::get('tenant/notifications/digests', [EnterpriseNotificationController::class, 'digests']);
            Route::post('tenant/notifications/digests', [EnterpriseNotificationController::class, 'storeDigest']);
            Route::get('tenant/notifications/schedules', [EnterpriseNotificationController::class, 'schedules']);
            Route::post('tenant/notifications/schedules', [EnterpriseNotificationController::class, 'storeSchedule']);
            Route::get('tenant/notifications', [EnterpriseNotificationController::class, 'index']);
            Route::post('tenant/notifications', [EnterpriseNotificationController::class, 'store']);
            Route::patch('tenant/notifications/{notificationPublicId}/read', [EnterpriseNotificationController::class, 'markRead']);
            Route::patch('tenant/notifications/{notificationPublicId}/unread', [EnterpriseNotificationController::class, 'markUnread']);
            Route::get('tenant/notifications/{notificationPublicId}', [EnterpriseNotificationController::class, 'show']);
            Route::delete('tenant/notifications/{notificationPublicId}', [EnterpriseNotificationController::class, 'destroy']);
            Route::get('tenant/reference/{catalogKey}', [ReferenceDataController::class, 'catalog']);
            Route::get('tenant/reference/{catalogKey}/{code}', [ReferenceDataController::class, 'item']);
            Route::get('tenant/files/entity', [PlatformFileController::class, 'entity']);
            Route::get('tenant/files/download/{filePublicId}', [PlatformFileController::class, 'download']);
            Route::get('tenant/files', [PlatformFileController::class, 'index']);
            Route::post('tenant/files', [PlatformFileController::class, 'store']);
            Route::get('tenant/files/{filePublicId}', [PlatformFileController::class, 'show']);
            Route::patch('tenant/files/{filePublicId}', [PlatformFileController::class, 'update']);
            Route::delete('tenant/files/{filePublicId}', [PlatformFileController::class, 'destroy']);
            Route::get('tenant/jobs', [PlatformJobController::class, 'index']);
            Route::post('tenant/jobs', [PlatformJobController::class, 'store']);
            Route::get('tenant/jobs/{jobPublicId}', [PlatformJobController::class, 'show']);
            Route::patch('tenant/jobs/{jobPublicId}/cancel', [PlatformJobController::class, 'cancel']);
            Route::get('tenant/scheduled-tasks', [ScheduledTaskController::class, 'index']);
            Route::post('tenant/scheduled-tasks', [ScheduledTaskController::class, 'store']);
            Route::get('tenant/scheduled-tasks/{taskPublicId}', [ScheduledTaskController::class, 'show']);
            Route::patch('tenant/scheduled-tasks/{taskPublicId}/pause', [ScheduledTaskController::class, 'pause']);
            Route::patch('tenant/scheduled-tasks/{taskPublicId}/resume', [ScheduledTaskController::class, 'resume']);
            Route::delete('tenant/scheduled-tasks/{taskPublicId}', [ScheduledTaskController::class, 'destroy']);
            Route::get('tenant/scheduled-tasks/{taskPublicId}/runs', [ScheduledTaskController::class, 'runs']);
            Route::get('tenant/search/suggestions', [SearchController::class, 'suggestions']);
            Route::get('tenant/search/recent', [SearchController::class, 'recent']);
            Route::post('tenant/search/saved', [SearchController::class, 'storeSaved']);
            Route::get('tenant/search/saved', [SearchController::class, 'listSaved']);
            Route::delete('tenant/search/saved/{savedSearchPublicId}', [SearchController::class, 'destroySaved']);
            Route::get('tenant/search', [SearchController::class, 'index']);
            Route::get('tenant/workflows/categories', [WorkflowCategoryController::class, 'index']);
            Route::post('tenant/workflows/categories', [WorkflowCategoryController::class, 'store']);
            Route::get('tenant/workflows/definitions/{publicId}/versions', [WorkflowDefinitionController::class, 'versions']);
            Route::post('tenant/workflows/definitions/{publicId}/publish', [WorkflowDefinitionController::class, 'publish']);
            Route::post('tenant/workflows/definitions/{publicId}/execute', [WorkflowDefinitionController::class, 'execute']);
            Route::post('tenant/workflows/definitions/{publicId}/archive', [WorkflowDefinitionController::class, 'archive']);
            Route::get('tenant/workflows/definitions/{publicId}', [WorkflowDefinitionController::class, 'show']);
            Route::patch('tenant/workflows/definitions/{publicId}', [WorkflowDefinitionController::class, 'update']);
            Route::get('tenant/workflows/definitions', [WorkflowDefinitionController::class, 'index']);
            Route::post('tenant/workflows/definitions', [WorkflowDefinitionController::class, 'store']);
            Route::get('tenant/workflow-instances/{publicId}/history', [WorkflowInstanceController::class, 'history']);
            Route::post('tenant/workflow-instances/{publicId}/cancel', [WorkflowInstanceController::class, 'cancel']);
            Route::post('tenant/workflow-instances/{publicId}/resume', [WorkflowInstanceController::class, 'resume']);
            Route::get('tenant/workflow-instances/{publicId}', [WorkflowInstanceController::class, 'show']);
            Route::get('tenant/workflow-instances', [WorkflowInstanceController::class, 'index']);
            Route::get('tenant/human-tasks/inbox', [HumanTaskController::class, 'inbox']);
            Route::get('tenant/human-tasks/statistics', [HumanTaskController::class, 'statistics']);
            Route::get('tenant/human-tasks/{publicId}/history', [HumanTaskController::class, 'history']);
            Route::get('tenant/human-tasks/{publicId}/comments', [HumanTaskController::class, 'comments']);
            Route::post('tenant/human-tasks/{publicId}/comments', [HumanTaskController::class, 'addComment']);
            Route::post('tenant/human-tasks/{publicId}/open', [HumanTaskController::class, 'open']);
            Route::post('tenant/human-tasks/{publicId}/complete', [HumanTaskController::class, 'complete']);
            Route::post('tenant/human-tasks/{publicId}/cancel', [HumanTaskController::class, 'cancel']);
            Route::get('tenant/human-tasks/{publicId}', [HumanTaskController::class, 'show']);
            Route::get('tenant/human-tasks', [HumanTaskController::class, 'index']);
            Route::get('tenant/approvals/{publicId}', [ApprovalController::class, 'show']);
            Route::post('tenant/approvals/{publicId}/approve', [ApprovalController::class, 'approve']);
            Route::post('tenant/approvals/{publicId}/reject', [ApprovalController::class, 'reject']);
            Route::get('tenant/approvals', [ApprovalController::class, 'index']);
            Route::get('tenant/rules/evaluations', [EnterpriseBusinessRuleController::class, 'evaluations']);
            Route::get('tenant/rules/executions', [EnterpriseBusinessRuleController::class, 'executions']);
            Route::post('tenant/rules/evaluate', [EnterpriseBusinessRuleController::class, 'evaluate']);
            Route::post('tenant/rules/execute', [EnterpriseBusinessRuleController::class, 'execute']);
            Route::get('tenant/rules/sets', [EnterpriseBusinessRuleController::class, 'indexSets']);
            Route::post('tenant/rules/sets', [EnterpriseBusinessRuleController::class, 'storeSet']);
            Route::patch('tenant/rules/sets/{ruleSetPublicId}/enable', [EnterpriseBusinessRuleController::class, 'enableSet']);
            Route::patch('tenant/rules/sets/{ruleSetPublicId}/disable', [EnterpriseBusinessRuleController::class, 'disableSet']);
            Route::get('tenant/rules', [EnterpriseBusinessRuleController::class, 'index']);
            Route::post('tenant/rules', [EnterpriseBusinessRuleController::class, 'store']);
            Route::get('tenant/rules/{rulePublicId}', [EnterpriseBusinessRuleController::class, 'show']);
            Route::patch('tenant/rules/{rulePublicId}', [EnterpriseBusinessRuleController::class, 'update']);
            Route::patch('tenant/rules/{rulePublicId}/enable', [EnterpriseBusinessRuleController::class, 'enable']);
            Route::patch('tenant/rules/{rulePublicId}/disable', [EnterpriseBusinessRuleController::class, 'disable']);

            Route::get('tenant/integrations/health', [EnterpriseIntegrationController::class, 'health']);
            Route::get('tenant/integrations/statistics', [EnterpriseIntegrationController::class, 'statistics']);
            Route::get('tenant/integrations/events', [EnterpriseIntegrationController::class, 'indexEvents']);
            Route::post('tenant/integrations/events', [EnterpriseIntegrationController::class, 'storeEvent']);
            Route::post('tenant/integrations/events/{eventPublicId}/replay', [EnterpriseIntegrationController::class, 'replayEvent']);
            Route::get('tenant/integrations/connectors', [EnterpriseIntegrationController::class, 'indexConnectors']);
            Route::post('tenant/integrations/connectors', [EnterpriseIntegrationController::class, 'storeConnector']);
            Route::get('tenant/integrations/endpoints', [EnterpriseIntegrationController::class, 'indexEndpoints']);
            Route::post('tenant/integrations/endpoints', [EnterpriseIntegrationController::class, 'storeEndpoint']);
            Route::get('tenant/integrations/subscriptions', [EnterpriseIntegrationController::class, 'indexSubscriptions']);
            Route::post('tenant/integrations/subscriptions', [EnterpriseIntegrationController::class, 'storeSubscription']);
            Route::post('tenant/integrations/dispatches', [EnterpriseIntegrationController::class, 'storeDispatch']);
            Route::patch('tenant/integrations/dead-letters/{deadLetterPublicId}/resolve', [EnterpriseIntegrationController::class, 'resolveDeadLetter']);

            Route::get('tenant/workflows/automation/rules', [WorkflowAutomationController::class, 'indexRules']);
            Route::post('tenant/workflows/automation/rules', [WorkflowAutomationController::class, 'storeRule']);
            Route::patch('tenant/workflows/automation/rules/{publicId}/enable', [WorkflowAutomationController::class, 'enableRule']);
            Route::patch('tenant/workflows/automation/rules/{publicId}/disable', [WorkflowAutomationController::class, 'disableRule']);
            Route::delete('tenant/workflows/automation/rules/{publicId}', [WorkflowAutomationController::class, 'destroyRule']);
            Route::get('tenant/workflows/automation/triggers', [WorkflowAutomationController::class, 'indexTriggers']);
            Route::get('tenant/workflows/automation/timers', [WorkflowAutomationController::class, 'indexTimers']);

            Route::get('tenant/workflows/designer/definitions/{definitionPublicId}/preview', [WorkflowDesignerController::class, 'preview']);
            Route::get('tenant/workflows/designer/definitions/{definitionPublicId}/canvas', [WorkflowDesignerController::class, 'showCanvas']);
            Route::post('tenant/workflows/designer/definitions/{definitionPublicId}/canvas', [WorkflowDesignerController::class, 'storeCanvas']);
            Route::get('tenant/workflows/designer/definitions/{definitionPublicId}/snapshots', [WorkflowDesignerController::class, 'indexSnapshots']);
            Route::get('tenant/workflows/designer/snapshots/{snapshotPublicId}', [WorkflowDesignerController::class, 'showSnapshot']);
            Route::get('tenant/workflows/designer/snapshots/{fromPublicId}/diff/{toPublicId}', [WorkflowDesignerController::class, 'diffSnapshots']);
            Route::post('tenant/workflows/designer/definitions/{definitionPublicId}/clone', [WorkflowDesignerController::class, 'clone']);
            Route::get('tenant/workflows/designer/definitions/{definitionPublicId}/export', [WorkflowDesignerController::class, 'export']);
            Route::post('tenant/workflows/designer/import', [WorkflowDesignerController::class, 'import']);
            Route::get('tenant/workflows/designer/node-templates', [WorkflowDesignerController::class, 'indexNodeTemplates']);

            Route::get('tenant/workflows/marketplace/installed', [WorkflowMarketplaceController::class, 'installed']);
            Route::get('tenant/workflows/marketplace/updates', [WorkflowMarketplaceController::class, 'updates']);
            Route::post('tenant/workflows/marketplace/import', [WorkflowMarketplaceController::class, 'import']);
            Route::get('tenant/workflows/marketplace', [WorkflowMarketplaceController::class, 'index']);
            Route::post('tenant/workflows/marketplace', [WorkflowMarketplaceController::class, 'store']);
            Route::get('tenant/workflows/marketplace/{packagePublicId}', [WorkflowMarketplaceController::class, 'show']);
            Route::post('tenant/workflows/marketplace/{packagePublicId}/versions', [WorkflowMarketplaceController::class, 'publishVersion']);
            Route::get('tenant/workflows/marketplace/{packagePublicId}/export', [WorkflowMarketplaceController::class, 'export']);
            Route::post('tenant/workflows/marketplace/{packagePublicId}/install', [WorkflowMarketplaceController::class, 'install']);
            Route::get('tenant/workflows/marketplace/{packagePublicId}/compatibility', [WorkflowMarketplaceController::class, 'compatibility']);
            Route::post('tenant/workflows/marketplace/installs/{installPublicId}/upgrade', [WorkflowMarketplaceController::class, 'upgrade']);
            Route::post('tenant/workflows/marketplace/installs/{installPublicId}/rollback', [WorkflowMarketplaceController::class, 'rollback']);
            Route::delete('tenant/workflows/marketplace/installs/{installPublicId}', [WorkflowMarketplaceController::class, 'destroy']);

            Route::get('tenant/forms/submissions/{submissionPublicId}', [DynamicFormController::class, 'showSubmission']);
            Route::delete('tenant/forms/drafts/{draftPublicId}', [DynamicFormController::class, 'destroyDraft']);
            Route::get('tenant/forms', [DynamicFormController::class, 'index']);
            Route::get('tenant/forms/{moduleKey}/{formKey}', [DynamicFormController::class, 'show']);
            Route::get('tenant/forms/{moduleKey}/{formKey}/render', [DynamicFormController::class, 'render']);
            Route::post('tenant/forms/{moduleKey}/{formKey}/validate', [DynamicFormController::class, 'validateSubmission']);
            Route::post('tenant/forms/{moduleKey}/{formKey}/submit', [DynamicFormController::class, 'submit']);
            Route::post('tenant/forms/{moduleKey}/{formKey}/drafts', [DynamicFormController::class, 'storeDraft']);
            Route::get('tenant/forms/{moduleKey}/{formKey}/drafts/latest', [DynamicFormController::class, 'latestDraft']);
            Route::get('tenant/forms/{moduleKey}/{formKey}/submissions', [DynamicFormController::class, 'submissions']);

            Route::delete('tenant/tables/views/{viewPublicId}', [DynamicTableController::class, 'destroyView']);
            Route::get('tenant/tables', [DynamicTableController::class, 'index']);
            Route::get('tenant/tables/{moduleKey}/{tableKey}', [DynamicTableController::class, 'show']);
            Route::get('tenant/tables/{moduleKey}/{tableKey}/render', [DynamicTableController::class, 'render']);
            Route::post('tenant/tables/{moduleKey}/{tableKey}/query', [DynamicTableController::class, 'query']);
            Route::get('tenant/tables/{moduleKey}/{tableKey}/views', [DynamicTableController::class, 'views']);
            Route::post('tenant/tables/{moduleKey}/{tableKey}/views', [DynamicTableController::class, 'storeView']);

            Route::delete('tenant/dashboards/views/{viewPublicId}', [DynamicDashboardController::class, 'destroyView']);
            Route::patch('tenant/dashboards/views/{viewPublicId}/default', [DynamicDashboardController::class, 'setDefaultView']);
            Route::patch('tenant/dashboards/widgets/{widgetPublicId}', [DynamicDashboardController::class, 'updateWidget']);
            Route::delete('tenant/dashboards/widgets/{widgetPublicId}', [DynamicDashboardController::class, 'destroyWidget']);
            Route::get('tenant/dashboards', [DynamicDashboardController::class, 'index']);
            Route::get('tenant/dashboards/{moduleKey}/{dashboardKey}', [DynamicDashboardController::class, 'show']);
            Route::get('tenant/dashboards/{moduleKey}/{dashboardKey}/render', [DynamicDashboardController::class, 'render']);
            Route::post('tenant/dashboards/{moduleKey}/{dashboardKey}/widgets', [DynamicDashboardController::class, 'storeWidget']);
            Route::get('tenant/dashboards/{moduleKey}/{dashboardKey}/widgets', [DynamicDashboardController::class, 'widgets']);
            Route::post('tenant/dashboards/{moduleKey}/{dashboardKey}/views', [DynamicDashboardController::class, 'storeView']);
            Route::get('tenant/dashboards/{moduleKey}/{dashboardKey}/views', [DynamicDashboardController::class, 'views']);

            Route::patch('tenant/reports/schedules/{schedulePublicId}/pause', [DynamicReportController::class, 'pauseSchedule']);
            Route::patch('tenant/reports/schedules/{schedulePublicId}/resume', [DynamicReportController::class, 'resumeSchedule']);
            Route::delete('tenant/reports/schedules/{schedulePublicId}', [DynamicReportController::class, 'destroySchedule']);
            Route::get('tenant/reports/runs/{runPublicId}', [DynamicReportController::class, 'showRun']);
            Route::get('tenant/reports/exports/{exportPublicId}', [DynamicReportController::class, 'showExport']);
            Route::get('tenant/reports', [DynamicReportController::class, 'index']);
            Route::get('tenant/reports/{moduleKey}/{reportKey}', [DynamicReportController::class, 'show']);
            Route::get('tenant/reports/{moduleKey}/{reportKey}/render', [DynamicReportController::class, 'render']);
            Route::post('tenant/reports/{moduleKey}/{reportKey}/run', [DynamicReportController::class, 'run']);
            Route::post('tenant/reports/{moduleKey}/{reportKey}/export', [DynamicReportController::class, 'export']);
            Route::get('tenant/reports/{moduleKey}/{reportKey}/runs', [DynamicReportController::class, 'runs']);
            Route::get('tenant/reports/{moduleKey}/{reportKey}/exports', [DynamicReportController::class, 'exports']);
            Route::post('tenant/reports/{moduleKey}/{reportKey}/schedules', [DynamicReportController::class, 'storeSchedule']);
            Route::get('tenant/reports/{moduleKey}/{reportKey}/schedules', [DynamicReportController::class, 'schedules']);

            Route::get('tenant/entities/tags', [EnterpriseEntityController::class, 'tags']);
            Route::post('tenant/entities/tags', [EnterpriseEntityController::class, 'storeTag']);
            Route::delete('tenant/entities/comments/{commentPublicId}', [EnterpriseEntityController::class, 'destroyComment']);
            Route::get('tenant/entities', [EnterpriseEntityController::class, 'index']);
            Route::get('tenant/entities/{moduleKey}/{entityKey}', [EnterpriseEntityController::class, 'show']);
            Route::get('tenant/entities/{moduleKey}/{entityKey}/relationships', [EnterpriseEntityController::class, 'relationships']);
            Route::post('tenant/entities/{moduleKey}/{entityKey}/relationships', [EnterpriseEntityController::class, 'storeRelationship']);
            Route::get('tenant/entities/{moduleKey}/{entityKey}/{entityPublicId}/activity', [EnterpriseEntityController::class, 'activity']);
            Route::get('tenant/entities/{moduleKey}/{entityKey}/{entityPublicId}/comments', [EnterpriseEntityController::class, 'comments']);
            Route::post('tenant/entities/{moduleKey}/{entityKey}/{entityPublicId}/comments', [EnterpriseEntityController::class, 'storeComment']);
            Route::post('tenant/entities/{moduleKey}/{entityKey}/{entityPublicId}/tags/{tagPublicId}', [EnterpriseEntityController::class, 'attachTag']);
            Route::delete('tenant/entities/{moduleKey}/{entityKey}/{entityPublicId}/tags/{tagPublicId}', [EnterpriseEntityController::class, 'detachTag']);

            Route::delete('tenant/documents/attachments/{attachmentPublicId}', [EnterpriseDocumentController::class, 'destroyAttachment']);
            Route::get('tenant/documents', [EnterpriseDocumentController::class, 'index']);
            Route::post('tenant/documents', [EnterpriseDocumentController::class, 'store']);
            Route::get('tenant/documents/health', [EnterpriseDocumentController::class, 'health']);
            Route::get('tenant/documents/statistics', [EnterpriseDocumentController::class, 'statistics']);
            Route::get('tenant/documents/{documentPublicId}', [EnterpriseDocumentController::class, 'show']);
            Route::patch('tenant/documents/{documentPublicId}', [EnterpriseDocumentController::class, 'update']);
            Route::delete('tenant/documents/{documentPublicId}', [EnterpriseDocumentController::class, 'destroy']);
            Route::get('tenant/documents/{documentPublicId}/versions', [EnterpriseDocumentController::class, 'versions']);
            Route::post('tenant/documents/{documentPublicId}/versions', [EnterpriseDocumentController::class, 'storeVersion']);
            Route::post('tenant/documents/{documentPublicId}/versions/{versionPublicId}/restore', [EnterpriseDocumentController::class, 'restoreVersion']);
            Route::get('tenant/documents/{documentPublicId}/attachments', [EnterpriseDocumentController::class, 'attachments']);
            Route::post('tenant/documents/{documentPublicId}/attachments', [EnterpriseDocumentController::class, 'storeAttachment']);
            Route::post('tenant/documents/{documentPublicId}/preview', [EnterpriseDocumentController::class, 'preview']);
            Route::post('tenant/documents/{documentPublicId}/thumbnail', [EnterpriseDocumentController::class, 'thumbnail']);
            Route::post('tenant/documents/{documentPublicId}/scan', [EnterpriseDocumentController::class, 'scan']);
            Route::post('tenant/documents/{documentPublicId}/ocr', [EnterpriseDocumentController::class, 'ocr']);
            Route::get('tenant/documents/{documentPublicId}/activity', [EnterpriseDocumentController::class, 'activity']);

            Route::delete('tenant/data/links/{linkPublicId}', [EnterpriseEntityRecordController::class, 'destroyLink']);
            Route::get('tenant/data/{moduleKey}/{entityKey}', [EnterpriseEntityRecordController::class, 'index']);
            Route::post('tenant/data/{moduleKey}/{entityKey}', [EnterpriseEntityRecordController::class, 'store']);
            Route::get('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}', [EnterpriseEntityRecordController::class, 'show']);
            Route::patch('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}', [EnterpriseEntityRecordController::class, 'update']);
            Route::delete('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}', [EnterpriseEntityRecordController::class, 'destroy']);
            Route::post('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}/restore', [EnterpriseEntityRecordController::class, 'restore']);
            Route::get('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}/versions', [EnterpriseEntityRecordController::class, 'versions']);
            Route::get('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}/activity', [EnterpriseEntityRecordController::class, 'activity']);
            Route::post('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}/links', [EnterpriseEntityRecordController::class, 'storeLink']);
            Route::get('tenant/data/{moduleKey}/{entityKey}/{recordPublicId}/links', [EnterpriseEntityRecordController::class, 'links']);

            Route::get('tenant/business-modules/installed', [BusinessModuleController::class, 'installed']);
            Route::get('tenant/business-modules', [BusinessModuleController::class, 'index']);
            Route::get('tenant/business-modules/{modulePublicId}', [BusinessModuleController::class, 'show']);
            Route::post('tenant/business-modules/{modulePublicId}/install', [BusinessModuleController::class, 'install']);
            Route::post('tenant/business-modules/installations/{installationPublicId}/enable', [BusinessModuleController::class, 'enable']);
            Route::post('tenant/business-modules/installations/{installationPublicId}/disable', [BusinessModuleController::class, 'disable']);
            Route::delete('tenant/business-modules/installations/{installationPublicId}', [BusinessModuleController::class, 'destroy']);
        });
    });
});
