<?php

namespace App\Providers;

use App\Modules\Sdk\Enterprise\Contracts\EventBusPort;
use App\Modules\Sdk\Enterprise\Contracts\FileServicePort;
use App\Modules\Sdk\Enterprise\Contracts\IndexPort;
use App\Modules\Sdk\Enterprise\Contracts\NotificationPort;
use App\Modules\Sdk\Enterprise\Contracts\PlatformJobPort;
use App\Modules\Sdk\Enterprise\Contracts\ReferenceDataPort;
use App\Modules\Sdk\Enterprise\Contracts\SchedulerPort;
use App\Modules\Sdk\Enterprise\Contracts\SearchPort;
use App\Modules\Sdk\Enterprise\Contracts\StoragePort;
use App\Modules\Sdk\Workflow\Contracts\WorkflowPort;
use App\Modules\Sdk\Workflow\Contracts\WorkflowValidator;
use App\Services\Enterprise\Audit\EnterprisePlatformJobAuditRecorder;
use App\Services\Enterprise\Audit\EnterpriseSchedulerAuditRecorder;
use App\Services\Enterprise\Audit\EnterpriseSearchAuditRecorder;
use App\Services\Enterprise\EventBus\EventBusService;
use App\Services\Enterprise\EventBus\LaravelEventBusAdapter;
use App\Services\Enterprise\EventBus\PlatformEventMapper;
use App\Services\Enterprise\EventBus\PlatformEventProcessor;
use App\Services\Enterprise\FileMedia\EnterpriseStorageHealthService;
use App\Services\Enterprise\FileMedia\FileCategoryClassifier;
use App\Services\Enterprise\FileMedia\FileQueryService;
use App\Services\Enterprise\FileMedia\FileService;
use App\Services\Enterprise\FileMedia\FileVisibilityResolver;
use App\Services\Enterprise\FileMedia\LaravelFileServiceAdapter;
use App\Services\Enterprise\FileMedia\LaravelStorageAdapter;
use App\Services\Enterprise\Jobs\LaravelPlatformJobAdapter;
use App\Services\Enterprise\Jobs\PlatformJobHandlerRegistry;
use App\Services\Enterprise\Jobs\PlatformJobHealthService;
use App\Services\Enterprise\Jobs\PlatformJobQueryService;
use App\Services\Enterprise\Jobs\PlatformJobService;
use App\Services\Enterprise\Jobs\PlatformJobTracker;
use App\Services\Enterprise\Notification\InAppNotificationChannel;
use App\Services\Enterprise\Notification\LaravelNotificationAdapter;
use App\Services\Enterprise\Notification\LogEmailNotificationChannel;
use App\Services\Enterprise\Notification\NotificationQueryService;
use App\Services\Enterprise\Notification\NotificationService;
use App\Services\Enterprise\ReferenceData\LaravelReferenceDataAdapter;
use App\Services\Enterprise\ReferenceData\ReferenceCatalogRegistry;
use App\Services\Enterprise\ReferenceData\ReferenceDataService;
use App\Services\Enterprise\Runtime\EnterpriseRuntimeBridge;
use App\Services\Enterprise\Runtime\EnterpriseRuntimeContextFactory;
use App\Services\Enterprise\Scheduler\LaravelSchedulerAdapter;
use App\Services\Enterprise\Scheduler\ScheduleExpressionHelper;
use App\Services\Enterprise\Scheduler\ScheduledTaskRunner;
use App\Services\Enterprise\Scheduler\SchedulerHealthService;
use App\Services\Enterprise\Scheduler\SchedulerService;
use App\Services\Enterprise\Search\LaravelSearchAdapter;
use App\Services\Enterprise\Search\SearchHealthService;
use App\Services\Enterprise\Search\SearchIndexService;
use App\Services\Enterprise\Search\SearchModuleRegistry;
use App\Services\Enterprise\Search\SearchService;
use App\Services\Enterprise\Search\SearchVisibilityResolver;
use App\Services\Enterprise\Support\EnterpriseTableHealthGuard;
use App\Services\Enterprise\Workflow\Automation\LaravelWorkflowAutomationAdapter;
use App\Services\Enterprise\Workflow\Automation\WorkflowAutomationAuditRecorder;
use App\Services\Enterprise\Workflow\Automation\WorkflowAutomationHealthService;
use App\Services\Enterprise\Workflow\Automation\WorkflowAutomationIntegrations;
use App\Services\Enterprise\Workflow\Automation\WorkflowAutomationService;
use App\Services\Enterprise\Workflow\Automation\WorkflowAutomationStatisticsService;
use App\Services\Enterprise\Workflow\Automation\WorkflowEventTriggerService;
use App\Services\Enterprise\Workflow\Automation\WorkflowScheduledTriggerService;
use App\Services\Enterprise\Workflow\Automation\WorkflowTimerRunner;
use App\Services\Enterprise\Workflow\Automation\WorkflowTimerService;
use App\Services\Enterprise\Workflow\Automation\WorkflowTriggerService;
use App\Services\Enterprise\Workflow\Human\ApprovalService;
use App\Services\Enterprise\Workflow\Human\DefaultAssignmentStrategy;
use App\Services\Enterprise\Workflow\Human\HumanTaskAuditRecorder;
use App\Services\Enterprise\Workflow\Human\HumanTaskHealthService;
use App\Services\Enterprise\Workflow\Human\HumanTaskIntegrations;
use App\Services\Enterprise\Workflow\Human\HumanTaskRuntimeBridge;
use App\Services\Enterprise\Workflow\Human\HumanTaskService;
use App\Services\Enterprise\Workflow\Human\HumanTaskStatisticsService;
use App\Services\Enterprise\Workflow\Human\LaravelApprovalPortAdapter;
use App\Services\Enterprise\Workflow\Human\LaravelHumanTaskAdapter;
use App\Services\Enterprise\Workflow\Human\TaskAssignmentService;
use App\Services\Enterprise\Workflow\Human\TaskEscalationService;
use App\Services\Enterprise\Workflow\Human\TaskHistoryService;
use App\Services\Enterprise\Workflow\Human\TaskInboxService;
use App\Services\Enterprise\Workflow\Human\WorkflowHumanTaskCompletionHandler;
use App\Services\Enterprise\Workflow\LaravelWorkflowAdapter;
use App\Services\Enterprise\Workflow\WorkflowAuditRecorder;
use App\Services\Enterprise\Workflow\WorkflowCategoryService;
use App\Services\Enterprise\Workflow\WorkflowDefinitionService;
use App\Services\Enterprise\Workflow\WorkflowHealthService;
use App\Services\Enterprise\Workflow\WorkflowSearchIndexer;
use App\Services\Enterprise\Workflow\WorkflowStatisticsService;
use App\Services\Enterprise\Workflow\WorkflowValidationService;
use App\Services\Enterprise\Workflow\WorkflowVersionService;
use App\Services\Enterprise\Workflow\Runtime\DefaultWorkflowExecutionHandler;
use App\Services\Enterprise\Workflow\Runtime\LaravelWorkflowRuntimeAdapter;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionAuditRecorder;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionContextBuilder;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionEngine;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionLogger;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionStatisticsService;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionTracker;
use App\Services\Enterprise\Workflow\Runtime\WorkflowExecutionVariableResolver;
use App\Services\Enterprise\Workflow\Runtime\WorkflowRuntimeHealthService;
use App\Services\Enterprise\Workflow\Runtime\WorkflowRuntimeIntegrations;
use App\Services\Enterprise\Workflow\Runtime\WorkflowRuntimeService;
use Illuminate\Support\ServiceProvider;

class EnterpriseServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(ReferenceCatalogRegistry::class);
        $this->app->singleton(EnterpriseRuntimeContextFactory::class);
        $this->app->singleton(EnterpriseRuntimeBridge::class);
        $this->app->singleton(PlatformEventMapper::class);
        $this->app->singleton(NotificationQueryService::class);

        $this->app->singleton(PlatformEventProcessor::class, function ($app) {
            return new PlatformEventProcessor(
                subscribers: [
                    $app->make(WorkflowEventTriggerService::class),
                ],
                auditRecorder: $app->make(\App\Services\Enterprise\Audit\EnterpriseEventAuditRecorder::class),
                mapper: $app->make(PlatformEventMapper::class),
            );
        });

        $this->app->singleton(LaravelEventBusAdapter::class);
        $this->app->singleton(LaravelNotificationAdapter::class, function ($app) {
            return new LaravelNotificationAdapter(
                channels: [
                    'in_app' => $app->make(InAppNotificationChannel::class),
                    'log_email' => $app->make(LogEmailNotificationChannel::class),
                ],
                auditRecorder: $app->make(\App\Services\Enterprise\Audit\EnterpriseNotificationAuditRecorder::class),
            );
        });
        $this->app->singleton(LaravelReferenceDataAdapter::class);

        $this->app->singleton(FileCategoryClassifier::class);
        $this->app->singleton(FileQueryService::class);
        $this->app->singleton(FileVisibilityResolver::class);
        $this->app->singleton(EnterpriseTableHealthGuard::class);
        $this->app->singleton(\App\Services\Enterprise\Support\EnterpriseDashboardHealthGuard::class);
        $this->app->singleton(\App\Services\Enterprise\Support\EnterpriseReportHealthGuard::class);
        $this->app->singleton(EnterpriseStorageHealthService::class);
        $this->app->singleton(LaravelStorageAdapter::class);
        $this->app->singleton(LaravelFileServiceAdapter::class);

        $this->app->singleton(StoragePort::class, LaravelStorageAdapter::class);
        $this->app->singleton(FileServicePort::class, LaravelFileServiceAdapter::class);
        $this->app->singleton(FileService::class);

        $this->app->singleton(PlatformJobHandlerRegistry::class);
        $this->app->singleton(PlatformJobTracker::class);
        $this->app->singleton(PlatformJobQueryService::class);
        $this->app->singleton(PlatformJobHealthService::class);
        $this->app->singleton(LaravelPlatformJobAdapter::class);
        $this->app->singleton(PlatformJobPort::class, LaravelPlatformJobAdapter::class);
        $this->app->singleton(PlatformJobService::class);

        $this->app->singleton(ScheduleExpressionHelper::class);
        $this->app->singleton(ScheduledTaskRunner::class);
        $this->app->singleton(SchedulerHealthService::class);
        $this->app->singleton(LaravelSchedulerAdapter::class);
        $this->app->singleton(SchedulerPort::class, LaravelSchedulerAdapter::class);
        $this->app->singleton(SchedulerService::class);

        $this->app->singleton(SearchModuleRegistry::class);
        $this->app->singleton(SearchVisibilityResolver::class);
        $this->app->singleton(SearchHealthService::class);
        $this->app->singleton(LaravelSearchAdapter::class);
        $this->app->singleton(SearchPort::class, LaravelSearchAdapter::class);
        $this->app->singleton(IndexPort::class, LaravelSearchAdapter::class);
        $this->app->singleton(SearchService::class);
        $this->app->singleton(SearchIndexService::class);

        $this->app->singleton(WorkflowValidationService::class);
        $this->app->singleton(WorkflowValidator::class, WorkflowValidationService::class);
        $this->app->singleton(WorkflowVersionService::class);
        $this->app->singleton(WorkflowStatisticsService::class);
        $this->app->singleton(WorkflowHealthService::class);
        $this->app->singleton(WorkflowAuditRecorder::class);
        $this->app->singleton(WorkflowSearchIndexer::class);
        $this->app->singleton(LaravelWorkflowAdapter::class);
        $this->app->singleton(WorkflowPort::class, LaravelWorkflowAdapter::class);
        $this->app->singleton(WorkflowDefinitionService::class);
        $this->app->singleton(WorkflowCategoryService::class);

        $this->app->singleton(DefaultWorkflowExecutionHandler::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Runtime\Contracts\WorkflowExecutionHandler::class, DefaultWorkflowExecutionHandler::class);
        $this->app->singleton(WorkflowExecutionTracker::class);
        $this->app->singleton(WorkflowExecutionLogger::class);
        $this->app->singleton(WorkflowExecutionVariableResolver::class);
        $this->app->singleton(WorkflowExecutionContextBuilder::class);
        $this->app->singleton(WorkflowExecutionAuditRecorder::class);
        $this->app->singleton(WorkflowExecutionEngine::class);
        $this->app->singleton(WorkflowExecutionStatisticsService::class);
        $this->app->singleton(WorkflowRuntimeHealthService::class);
        $this->app->singleton(WorkflowRuntimeIntegrations::class);
        $this->app->singleton(LaravelWorkflowRuntimeAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Runtime\Contracts\WorkflowRuntimePort::class, LaravelWorkflowRuntimeAdapter::class);
        $this->app->singleton(WorkflowRuntimeService::class);

        $this->app->singleton(DefaultAssignmentStrategy::class);
        $this->app->singleton(TaskAssignmentService::class);
        $this->app->singleton(TaskHistoryService::class);
        $this->app->singleton(TaskEscalationService::class);
        $this->app->singleton(HumanTaskStatisticsService::class);
        $this->app->singleton(HumanTaskAuditRecorder::class);
        $this->app->singleton(LaravelHumanTaskAdapter::class);
        $this->app->singleton(LaravelApprovalPortAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Human\Contracts\HumanTaskPort::class, LaravelHumanTaskAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Human\Contracts\ApprovalPort::class, LaravelApprovalPortAdapter::class);
        $this->app->singleton(HumanTaskIntegrations::class);
        $this->app->singleton(HumanTaskHealthService::class);
        $this->app->singleton(WorkflowHumanTaskCompletionHandler::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Human\Contracts\ApprovalDecisionHandler::class, WorkflowHumanTaskCompletionHandler::class);
        $this->app->singleton(HumanTaskRuntimeBridge::class);
        $this->app->singleton(HumanTaskService::class);
        $this->app->singleton(ApprovalService::class);
        $this->app->singleton(TaskInboxService::class);

        $this->app->singleton(WorkflowAutomationStatisticsService::class);
        $this->app->singleton(WorkflowAutomationAuditRecorder::class);
        $this->app->singleton(WorkflowAutomationIntegrations::class);
        $this->app->singleton(WorkflowTriggerService::class);
        $this->app->singleton(WorkflowScheduledTriggerService::class);
        $this->app->singleton(LaravelWorkflowAutomationAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Automation\Contracts\WorkflowAutomationPort::class, LaravelWorkflowAutomationAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Automation\Contracts\WorkflowTriggerHandler::class, WorkflowTriggerService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Automation\Contracts\WorkflowTimerHandler::class, WorkflowTimerService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Automation\Contracts\WorkflowEventTriggerProvider::class, WorkflowEventTriggerService::class);
        $this->app->singleton(WorkflowEventTriggerService::class);
        $this->app->singleton(WorkflowTimerService::class);
        $this->app->singleton(WorkflowAutomationHealthService::class);
        $this->app->singleton(WorkflowAutomationService::class);
        $this->app->singleton(WorkflowTimerRunner::class);

        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowCanvasNormalizationService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Designer\Contracts\WorkflowCanvasNormalizer::class, \App\Services\Enterprise\Workflow\Designer\WorkflowCanvasNormalizationService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowCanvasDiffService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowCanvasService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowCloneService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowImportExportService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowNodeTemplateService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Designer\Contracts\WorkflowTemplateProvider::class, \App\Services\Enterprise\Workflow\Designer\WorkflowNodeTemplateService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowDesignerPreviewService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowDesignerHealthService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowDesignerAuditRecorder::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowDesignerSearchIndexer::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\LaravelWorkflowDesignerAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Designer\Contracts\WorkflowDesignerPort::class, \App\Services\Enterprise\Workflow\Designer\LaravelWorkflowDesignerAdapter::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Designer\WorkflowDesignerService::class);

        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageValidatorService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowPackageValidator::class, \App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageValidatorService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageProviderService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowPackageProvider::class, \App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageProviderService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowCompatibilityService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowDependencyResolverService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowDependencyResolver::class, \App\Services\Enterprise\Workflow\Marketplace\WorkflowDependencyResolverService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowMarketplaceAuditRecorder::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowMarketplaceSearchIndexer::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageStatisticsService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageHealthService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageExporterService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowPackageExporter::class, \App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageExporterService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageInstallerService::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowPackageInstaller::class, \App\Services\Enterprise\Workflow\Marketplace\WorkflowPackageInstallerService::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\LaravelWorkflowMarketplaceAdapter::class);
        $this->app->singleton(\App\Modules\Sdk\Workflow\Marketplace\Contracts\WorkflowMarketplacePort::class, \App\Services\Enterprise\Workflow\Marketplace\LaravelWorkflowMarketplaceAdapter::class);
        $this->app->singleton(\App\Services\Enterprise\Workflow\Marketplace\WorkflowMarketplaceService::class);

        $this->app->singleton(\App\Services\Enterprise\Audit\EnterpriseFileAuditRecorder::class);
        $this->app->singleton(EnterprisePlatformJobAuditRecorder::class);
        $this->app->singleton(EnterpriseSchedulerAuditRecorder::class);
        $this->app->singleton(EnterpriseSearchAuditRecorder::class);

        $this->app->singleton(EventBusPort::class, LaravelEventBusAdapter::class);
        $this->app->singleton(NotificationPort::class, LaravelNotificationAdapter::class);
        $this->app->singleton(ReferenceDataPort::class, LaravelReferenceDataAdapter::class);

        $this->app->singleton(EventBusService::class);
        $this->app->singleton(NotificationService::class);
        $this->app->singleton(ReferenceDataService::class);

        $this->app->singleton(\App\Services\Enterprise\Audit\EnterpriseEventAuditRecorder::class);
        $this->app->singleton(\App\Services\Enterprise\Audit\EnterpriseNotificationAuditRecorder::class);
        $this->app->singleton(\App\Services\Enterprise\Audit\EnterpriseReferenceAuditRecorder::class);
        $this->app->singleton(InAppNotificationChannel::class);
        $this->app->singleton(LogEmailNotificationChannel::class);

        $this->app->singleton(\App\Services\Entity\EnterpriseEntityValidationService::class);
        $this->app->singleton(\App\Modules\Sdk\Entity\Contracts\EntityValidator::class, \App\Services\Entity\EnterpriseEntityValidationService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Entity\Contracts\EntityRegistry::class, \App\Services\Entity\EnterpriseEntityRegistryService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityRepositoryService::class);
        $this->app->singleton(\App\Modules\Sdk\Entity\Contracts\EntityRepository::class, \App\Services\Entity\EnterpriseEntityRepositoryService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityLifecycleService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityRelationshipService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityActivityService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityCommentService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityTagService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntitySearchIndexer::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityWorkflowBridge::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityAttachmentBridge::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityHealthService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityStatisticsService::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityAuditRecorder::class);
        $this->app->singleton(\App\Services\Entity\EnterpriseEntityDevelopmentService::class);

        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordValidationService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordValidator::class, \App\Services\DataRepository\EnterpriseEntityRecordValidationService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordRepositoryService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordRepository::class, \App\Services\DataRepository\EnterpriseEntityRecordRepositoryService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordQueryService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordQueryProvider::class, \App\Services\DataRepository\EnterpriseEntityRecordQueryService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordMutationService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordMutationHandler::class, \App\Services\DataRepository\EnterpriseEntityRecordMutationService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordLifecycleService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordLifecycleDispatcher::class, \App\Services\DataRepository\EnterpriseEntityRecordLifecycleService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordVersionService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordProjectionService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordProjectionProvider::class, \App\Services\DataRepository\EnterpriseEntityRecordProjectionService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordRelationshipService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordActivityService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordDataProviderService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordDataProvider::class, \App\Services\DataRepository\EnterpriseEntityRecordDataProviderService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordTableBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordDashboardBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordReportBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordFormBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordSearchIndexer::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordWorkflowBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordAttachmentBridge::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordAuditRecorder::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordHealthService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordStatisticsService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordPolicyResolverService::class);
        $this->app->singleton(\App\Modules\Sdk\DataRepository\Contracts\EntityRecordPolicyResolver::class, \App\Services\DataRepository\EnterpriseEntityRecordPolicyResolverService::class);
        $this->app->singleton(\App\Services\DataRepository\EnterpriseEntityRecordDevelopmentService::class);

        $this->app->singleton(\App\Services\Document\EnterpriseDocumentRepositoryService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentRepository::class, \App\Services\Document\EnterpriseDocumentRepositoryService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentStorageProviderService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentStorageProvider::class, \App\Services\Document\EnterpriseDocumentStorageProviderService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentVersionService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentVersionManager::class, \App\Services\Document\EnterpriseDocumentVersionService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseAttachmentService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\AttachmentRepository::class, \App\Services\Document\EnterpriseAttachmentService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentPreviewService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentPreviewProvider::class, \App\Services\Document\EnterpriseDocumentPreviewService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentThumbnailService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentThumbnailProvider::class, \App\Services\Document\EnterpriseDocumentThumbnailService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentScanService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentScanner::class, \App\Services\Document\EnterpriseDocumentScanService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentOcrService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentOcrProvider::class, \App\Services\Document\EnterpriseDocumentOcrService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentRetentionService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentRetentionPolicy::class, \App\Services\Document\EnterpriseDocumentRetentionService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentPermissionService::class);
        $this->app->singleton(\App\Modules\Sdk\Document\Contracts\DocumentPermissionResolver::class, \App\Services\Document\EnterpriseDocumentPermissionService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentUploadService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentActivityService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentAuditRecorder::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentQuotaService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentHealthService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentStatisticsService::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentSearchIndexer::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentWorkflowBridge::class);
        $this->app->singleton(\App\Services\Document\EnterpriseDocumentDevelopmentService::class);

        $this->app->singleton(\App\Services\Notification\NotificationRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationRenderer::class, \App\Services\Notification\NotificationRendererService::class);
        $this->app->singleton(\App\Services\Notification\NotificationTemplateService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationTemplateProvider::class, \App\Services\Notification\NotificationTemplateService::class);
        $this->app->singleton(\App\Services\Notification\NotificationPreferenceService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationPreferenceProvider::class, \App\Services\Notification\NotificationPreferenceService::class);
        $this->app->singleton(\App\Services\Notification\NotificationDeliveryService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationDeliveryTracker::class, \App\Services\Notification\NotificationDeliveryService::class);
        $this->app->singleton(\App\Services\Notification\NotificationQueueService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationQueue::class, \App\Services\Notification\NotificationQueueService::class);
        $this->app->singleton(\App\Services\Notification\NotificationScheduleService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationScheduler::class, \App\Services\Notification\NotificationScheduleService::class);
        $this->app->singleton(\App\Services\Notification\NotificationDigestService::class);
        $this->app->singleton(\App\Services\Notification\NotificationStatisticsService::class);
        $this->app->singleton(\App\Services\Notification\NotificationHealthService::class);
        $this->app->singleton(\App\Services\Notification\NotificationAuditRecorder::class);
        $this->app->singleton(\App\Services\Notification\NotificationSearchIndexer::class);
        $this->app->singleton(\App\Services\Notification\Providers\InAppProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\EmailProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\SmsProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\PushProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\WhatsappProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\SlackProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\TeamsProvider::class);
        $this->app->singleton(\App\Services\Notification\Providers\WebhookProvider::class);
        $this->app->singleton(\App\Services\Notification\EnterpriseNotificationService::class);
        $this->app->singleton(\App\Modules\Sdk\Notification\Contracts\NotificationPort::class, \App\Services\Notification\EnterpriseNotificationService::class);
        $this->app->singleton(\App\Services\Notification\EnterpriseNotificationPermissionService::class);
        $this->app->singleton(\App\Services\Notification\NotificationWorkflowBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationDocumentBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationReportBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationHumanTaskBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationApprovalBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationEntityBridge::class);
        $this->app->singleton(\App\Services\Notification\NotificationDevelopmentService::class);

        $this->app->singleton(\App\Services\Rules\RuleRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleRegistry::class, \App\Services\Rules\RuleRegistryService::class);
        $this->app->singleton(\App\Services\Rules\RuleSetService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleSetProvider::class, \App\Services\Rules\RuleSetService::class);
        $this->app->singleton(\App\Services\Rules\RuleDefinitionService::class);
        $this->app->singleton(\App\Services\Rules\RuleValidationService::class);
        $this->app->singleton(\App\Services\Rules\RuleConditionEvaluatorService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleConditionEvaluator::class, \App\Services\Rules\RuleConditionEvaluatorService::class);
        $this->app->singleton(\App\Services\Rules\RuleActionExecutorService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleActionExecutor::class, \App\Services\Rules\RuleActionExecutorService::class);
        $this->app->singleton(\App\Services\Rules\RuleContextService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleContextProvider::class, \App\Services\Rules\RuleContextService::class);
        $this->app->singleton(\App\Services\Rules\RuleFactService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleFactProvider::class, \App\Services\Rules\RuleFactService::class);
        $this->app->singleton(\App\Services\Rules\RuleEvaluationService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleEvaluator::class, \App\Services\Rules\RuleEvaluationService::class);
        $this->app->singleton(\App\Services\Rules\RuleExecutionService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleExecutor::class, \App\Services\Rules\RuleExecutionService::class);
        $this->app->singleton(\App\Services\Rules\RuleTraceService::class);
        $this->app->singleton(\App\Services\Rules\RulePolicyService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RulePolicyProvider::class, \App\Services\Rules\RulePolicyService::class);
        $this->app->singleton(\App\Services\Rules\RuleActivityService::class);
        $this->app->singleton(\App\Services\Rules\RuleSearchIndexer::class);
        $this->app->singleton(\App\Services\Rules\RuleAuditRecorder::class);
        $this->app->singleton(\App\Services\Rules\RuleHealthService::class);
        $this->app->singleton(\App\Services\Rules\RuleStatisticsService::class);
        $this->app->singleton(\App\Services\Rules\EnterpriseRuleEngineService::class);
        $this->app->singleton(\App\Modules\Sdk\Rules\Contracts\RuleEngine::class, \App\Services\Rules\EnterpriseRuleEngineService::class);
        $this->app->singleton(\App\Services\Rules\RulePermissionService::class);
        $this->app->singleton(\App\Services\Rules\RuleWorkflowBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleNotificationBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleDocumentBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleEntityBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleDataRepositoryBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleFormBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleReportBridge::class);
        $this->app->singleton(\App\Services\Rules\RuleDevelopmentService::class);

        $this->app->singleton(\App\Services\Integration\IntegrationValidationService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationActivityService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationAuditRecorder::class);
        $this->app->singleton(\App\Services\Integration\IntegrationStatisticsService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationHealthService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationPermissionService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationSearchIndexer::class);
        $this->app->singleton(\App\Services\Integration\IntegrationMapperService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationMapper::class, \App\Services\Integration\IntegrationMapperService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationTransformerService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationTransformer::class, \App\Services\Integration\IntegrationTransformerService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationCredentialService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationCredentialProvider::class, \App\Services\Integration\IntegrationCredentialService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationWebhookVerifierService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationWebhookVerifier::class, \App\Services\Integration\IntegrationWebhookVerifierService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationRetryPolicyService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationRetryPolicy::class, \App\Services\Integration\IntegrationRetryPolicyService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationDeadLetterService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationDeadLetterQueue::class, \App\Services\Integration\IntegrationDeadLetterService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationConnectorService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationConnector::class, \App\Services\Integration\IntegrationConnectorService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationEndpointService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationEndpoint::class, \App\Services\Integration\IntegrationEndpointService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationMappingService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationEventSubscriptionService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationEventSubscriber::class, \App\Services\Integration\IntegrationEventSubscriptionService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationEventPublisherService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationEventPublisher::class, \App\Services\Integration\IntegrationEventPublisherService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationDispatchService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationProcessingService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationReplayService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationEventBusBridge::class);
        $this->app->singleton(\App\Services\Integration\EnterpriseIntegrationEventBusService::class);
        $this->app->singleton(\App\Modules\Sdk\Integration\Contracts\IntegrationEventBus::class, \App\Services\Integration\EnterpriseIntegrationEventBusService::class);
        $this->app->singleton(\App\Services\Integration\EnterpriseIntegrationService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationDevelopmentService::class);
        $this->app->singleton(\App\Services\Integration\IntegrationEntityBridge::class);
        $this->app->singleton(\App\Services\Integration\IntegrationNotificationBridge::class);
        $this->app->singleton(\App\Services\Integration\IntegrationRulesBridge::class);

        $this->app->singleton(\App\Services\Application\ApplicationRuntimeMapper::class);
        $this->app->singleton(\App\Services\Application\ApplicationAuditRecorder::class);
        $this->app->singleton(\App\Services\Application\ApplicationSearchIndexer::class);
        $this->app->singleton(\App\Services\Application\ApplicationStatisticsService::class);
        $this->app->singleton(\App\Services\Application\ApplicationHealthService::class);
        $this->app->singleton(\App\Services\Application\ApplicationPermissionBridge::class);
        $this->app->singleton(\App\Services\Application\ApplicationRuntimeManifestService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\ApplicationManifestProvider::class, \App\Services\Application\ApplicationRuntimeManifestService::class);
        $this->app->singleton(\App\Services\Application\ApplicationDiscoveryService::class);
        $this->app->singleton(\App\Services\Application\ApplicationLoaderService::class);
        $this->app->singleton(\App\Services\Application\NavigationBuilderService::class);
        $this->app->singleton(\App\Services\Application\NavigationRegistryService::class);
        $this->app->singleton(\App\Services\Application\MenuBuilderService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\MenuProvider::class, \App\Services\Application\MenuBuilderService::class);
        $this->app->singleton(\App\Services\Application\WorkspaceManagerService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\WorkspaceProvider::class, \App\Services\Application\WorkspaceManagerService::class);
        $this->app->singleton(\App\Services\Application\ApplicationRuntimeRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\ApplicationRegistry::class, \App\Services\Application\ApplicationRuntimeRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\ApplicationLifecycle::class, \App\Services\Application\ApplicationRuntimeRegistryService::class);
        $this->app->singleton(\App\Services\Application\ApplicationRuntimeService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\ApplicationRuntime::class, \App\Services\Application\ApplicationRuntimeService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\NavigationProvider::class, \App\Services\Application\ApplicationRuntimeService::class);
        $this->app->singleton(\App\Services\Application\EnterpriseApplicationService::class);
        $this->app->singleton(\App\Modules\Sdk\Application\Contracts\ApplicationProvider::class, \App\Services\Application\EnterpriseApplicationService::class);
        $this->app->singleton(\App\Services\Application\ApplicationDevelopmentService::class);

        $this->app->singleton(\App\Services\Ui\UiMapper::class);
        $this->app->singleton(\App\Services\Ui\UiTableHealthSupport::class);
        $this->app->singleton(\App\Services\Ui\UiAuditRecorder::class);
        $this->app->singleton(\App\Services\Ui\UiSearchIndexer::class);
        $this->app->singleton(\App\Services\Ui\UiPlatformEventBridge::class);
        $this->app->singleton(\App\Services\Ui\UiStatisticsService::class);
        $this->app->singleton(\App\Services\Ui\UiHealthService::class);
        $this->app->singleton(\App\Services\Ui\UiPermissionBridge::class);
        $this->app->singleton(\App\Services\Ui\UiConditionEvaluatorService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiConditionEvaluator::class, \App\Services\Ui\UiConditionEvaluatorService::class);
        $this->app->singleton(\App\Services\Ui\UiActionService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiActionProvider::class, \App\Services\Ui\UiActionService::class);
        $this->app->singleton(\App\Services\Ui\UiThemeService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiThemeProvider::class, \App\Services\Ui\UiThemeService::class);
        $this->app->singleton(\App\Services\Ui\UiPersonalizationService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiPersonalizationProvider::class, \App\Services\Ui\UiPersonalizationService::class);
        $this->app->singleton(\App\Services\Ui\UiFormBridge::class);
        $this->app->singleton(\App\Services\Ui\UiTableBridge::class);
        $this->app->singleton(\App\Services\Ui\UiDashboardBridge::class);
        $this->app->singleton(\App\Services\Ui\UiReportBridge::class);
        $this->app->singleton(\App\Services\Ui\UiApplicationBridge::class);
        $this->app->singleton(\App\Services\Ui\UiRulesBridge::class);
        $this->app->singleton(\App\Services\Ui\UiWorkflowBridge::class);
        $this->app->singleton(\App\Services\Ui\UiPageRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiPageRegistry::class, \App\Services\Ui\UiPageRegistryService::class);
        $this->app->singleton(\App\Services\Ui\UiPageDefinitionService::class);
        $this->app->singleton(\App\Services\Ui\UiLayoutService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiLayoutProvider::class, \App\Services\Ui\UiLayoutService::class);
        $this->app->singleton(\App\Services\Ui\UiComponentService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiComponentProvider::class, \App\Services\Ui\UiComponentService::class);
        $this->app->singleton(\App\Services\Ui\UiRuntimeComposerService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiRuntimeComposer::class, \App\Services\Ui\UiRuntimeComposerService::class);
        $this->app->singleton(\App\Services\Ui\UiRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Ui\Contracts\UiRenderer::class, \App\Services\Ui\UiRendererService::class);
        $this->app->singleton(\App\Services\Ui\UiDevelopmentService::class);

        $this->app->singleton(\App\Services\Form\DynamicFormConditionEvaluator::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormConditionEvaluator::class, \App\Services\Form\DynamicFormConditionEvaluator::class);
        $this->app->singleton(\App\Services\Form\DynamicFormFieldResolver::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormFieldResolver::class, \App\Services\Form\DynamicFormFieldResolver::class);
        $this->app->singleton(\App\Services\Form\DynamicFormActionService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormValidationService::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormValidator::class, \App\Services\Form\DynamicFormValidationService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormRegistry::class, \App\Services\Form\DynamicFormRegistryService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormDefinitionService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormGeneratorService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormRenderer::class, \App\Services\Form\DynamicFormRendererService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormSubmissionService::class);
        $this->app->singleton(\App\Modules\Sdk\Form\Contracts\FormSubmissionHandler::class, \App\Services\Form\DynamicFormSubmissionService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormDraftService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormActivityService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormSearchIndexer::class);
        $this->app->singleton(\App\Services\Form\DynamicFormWorkflowBridge::class);
        $this->app->singleton(\App\Services\Form\DynamicFormHealthService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormStatisticsService::class);
        $this->app->singleton(\App\Services\Form\DynamicFormAuditRecorder::class);
        $this->app->singleton(\App\Services\Form\DynamicFormDevelopmentService::class);

        $this->app->singleton(\App\Services\Table\DynamicTableColumnResolver::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableColumnResolver::class, \App\Services\Table\DynamicTableColumnResolver::class);
        $this->app->singleton(\App\Services\Table\DynamicTableFilterEvaluator::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableFilterEvaluator::class, \App\Services\Table\DynamicTableFilterEvaluator::class);
        $this->app->singleton(\App\Services\Table\DynamicTableSortService::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableSortResolver::class, \App\Services\Table\DynamicTableSortService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableValidationService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableRegistry::class, \App\Services\Table\DynamicTableRegistryService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableDefinitionService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableGeneratorService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableRenderer::class, \App\Services\Table\DynamicTableRendererService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableQueryService::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableQueryExecutor::class, \App\Services\Table\DynamicTableQueryService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableViewService::class);
        $this->app->singleton(\App\Modules\Sdk\Table\Contracts\TableViewProvider::class, \App\Services\Table\DynamicTableViewService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableActionService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableActivityService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableSearchIndexer::class);
        $this->app->singleton(\App\Services\Table\DynamicTableWorkflowBridge::class);
        $this->app->singleton(\App\Services\Table\DynamicTableHealthService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableStatisticsService::class);
        $this->app->singleton(\App\Services\Table\DynamicTableAuditRecorder::class);
        $this->app->singleton(\App\Services\Table\DynamicTableDevelopmentService::class);

        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardFilterService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardFilterEvaluator::class, \App\Services\Dashboard\DynamicDashboardFilterService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardMetricService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardMetricResolver::class, \App\Services\Dashboard\DynamicDashboardMetricService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardLayoutService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardLayoutProvider::class, \App\Services\Dashboard\DynamicDashboardLayoutService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardValidationService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardRegistry::class, \App\Services\Dashboard\DynamicDashboardRegistryService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardDefinitionService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardGeneratorService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardGenerator::class, \App\Services\Dashboard\DynamicDashboardGeneratorService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardRenderer::class, \App\Services\Dashboard\DynamicDashboardRendererService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardDataProviderService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardDataProvider::class, \App\Services\Dashboard\DynamicDashboardDataProviderService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardWidgetService::class);
        $this->app->singleton(\App\Modules\Sdk\Dashboard\Contracts\DashboardWidgetProvider::class, \App\Services\Dashboard\DynamicDashboardWidgetService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardViewService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardQueryService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardActionService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardActivityService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardSearchIndexer::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardWorkflowBridge::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardHealthService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardStatisticsService::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardAuditRecorder::class);
        $this->app->singleton(\App\Services\Dashboard\DynamicDashboardDevelopmentService::class);

        $this->app->singleton(\App\Services\Report\DynamicReportFilterService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportFilterEvaluator::class, \App\Services\Report\DynamicReportFilterService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportAggregateService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportAggregateResolver::class, \App\Services\Report\DynamicReportAggregateService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportValidationService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportRegistryService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportRegistry::class, \App\Services\Report\DynamicReportRegistryService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportDefinitionService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportGeneratorService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportGenerator::class, \App\Services\Report\DynamicReportGeneratorService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportRendererService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportRenderer::class, \App\Services\Report\DynamicReportRendererService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportDataProviderService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportDataProvider::class, \App\Services\Report\DynamicReportDataProviderService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportQueryService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportGroupingService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportChartService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportTemplateService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportTemplateProvider::class, \App\Services\Report\DynamicReportTemplateService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportRunService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportExportService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportExporter::class, \App\Services\Report\DynamicReportExportService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportScheduleService::class);
        $this->app->singleton(\App\Modules\Sdk\Report\Contracts\ReportScheduler::class, \App\Services\Report\DynamicReportScheduleService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportActivityService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportSearchIndexer::class);
        $this->app->singleton(\App\Services\Report\DynamicReportWorkflowBridge::class);
        $this->app->singleton(\App\Services\Report\DynamicReportHealthService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportStatisticsService::class);
        $this->app->singleton(\App\Services\Report\DynamicReportAuditRecorder::class);
        $this->app->singleton(\App\Services\Report\DynamicReportDevelopmentService::class);
    }

    public function boot(): void
    {
        $this->app->booted(function () {
            $this->app->make(PlatformJobHandlerRegistry::class)->register(
                'workflow.automation.trigger',
                fn (\App\Models\PlatformJob $job) => $this->app->make(WorkflowScheduledTriggerService::class)->executeFromJob($job),
            );
        });
    }
}
